CREATE TABLE IF NOT EXISTS ratings
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50)                     NOT NULL,
    description  VARCHAR(50)                     NOT NULL,
    release_date DATE                            NOT NULL,
    duration     REAL                            NOT NULL,
    rating_id    INTEGER REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(50) NOT NULL,
    name     VARCHAR(50) NOT NULL,
    birthday DATE        NOT NULL,
    login    VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    films_id  INTEGER REFERENCES films (id),
    genres_id INTEGER REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS friends
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id)
);



