CREATE TABLE films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR                         NOT NULL,
    description  VARCHAR                         NOT NULL,
    release_date DATE                            NOT NULL,
    duration     REAL                            NOT NULL,
    rating_id    INTEGER REFERENCES ratings (id) NOT NULL
);

CREATE TABLE ratings
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR NOT NULL
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR NOT NULL,
    name     VARCHAR NOT NULL,
    birthday DATE    NOT NULL,
    login    VARCHAR NOT NULL
);

CREATE TABLE genres
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR NOT NULL
);

CREATE TABLE films_genres
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    film_id  INTEGER REFERENCES films (id) ON DELETE CASCADE,
);

CREATE TABLE likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
);

CREATE TABLE friends
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    status    BOOLEAN
);



